language: node_js
branches:
  only:
    - master
node_js:
  - "8.11.1"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - npm install -g npm@6.4.1
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run test
